name: macos

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  perl:

    runs-on: macOS-latest

    env:
       PERL_USE_UNSAFE_INC: 0
       AUTHOR_TESTING: 1
       AUTOMATED_TESTING: 1
       RELEASE_TESTING: 0
       PERL_CARTON_PATH: $GITHUB_WORKSPACE/local

    steps:
      - uses: actions/checkout@v2
      - name: Set up libcurl & Perl
        run: brew install cpanminus curl perl
      - name: perl -V
        run: perl -V
      - name: Install Dependencies
        run: |
          cpanm --notest --installdeps .
          cpanm --notest ExtUtils::PkgConfig
      - name: perl Makefile.PL
        run: |
          eval $( brew shellenv )
          export LDFLAGS="-L$HOMEBREW_PREFIX/opt/curl/lib"
          export CPPFLAGS="-I$HOMEBREW_PREFIX/opt/curl/include"
          export PKG_CONFIG_PATH="$HOMEBREW_PREFIX/opt/curl/lib/pkgconfig"
          perl Makefile.PL
      - name: make
        run: make
      - name: Run Tests
        run: make test
